version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

  #production_app_media: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
      #- production_app_media:/app/marketplace/media:z
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - .env
